SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

DROP TABLE IF EXISTS `visitor` ;

DROP TABLE IF EXISTS `team` ;

DROP TABLE IF EXISTS `project` ;

DROP TABLE IF EXISTS `portfolio` ;

DROP TABLE IF EXISTS `news` ;

DROP TABLE IF EXISTS `filestore_volume` ;

DROP TABLE IF EXISTS `filestore_type` ;

DROP TABLE IF EXISTS `filestore_image` ;

DROP TABLE IF EXISTS `filestore_file` ;

DROP TABLE IF EXISTS `content` ;

DROP TABLE IF EXISTS `blog_comment` ;

DROP TABLE IF EXISTS `blog` ;

DROP TABLE IF EXISTS `atk_moreinfo` ;

DROP TABLE IF EXISTS `atk_maillog` ;

DROP TABLE IF EXISTS `atk_donation` ;

DROP TABLE IF EXISTS `admin` ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

